prjMSIT145-Final/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using prjMSIT145Final.Infrastructure.Models;
using prjMSIT145Final.Web.ViewModels;
using System.Net.Mail;
using System.Text;

namespace prjMSIT145Final.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ispanMsit145shibaContext _context;
        private readonly IConfiguration _config;
        public CouponController(ispanMsit145shibaContext context, IConfiguration config)
        {
            _context = context;
            _config = config;
        }
        public IActionResult Index()
        {           
            return View();
        }
        
        public IActionResult ACouponList()
        {
            List<CACouponViewModel> list = new List<CACouponViewModel>();            

            var coupons = from c in _context.Coupons
                          join cn in _context.Coupon2NormalMembers on c.Fid equals cn.CouponId
                          into sGroup
                          from s in sGroup.DefaultIfEmpty()
                          join n in _context.NormalMembers on s.MemberId equals n.Fid
                          into sg2
                          from sg in sg2.DefaultIfEmpty()
                          select new
                          {
                              c.Fid,
                              c.Price,
                              c.CouponCode,
                              c.Title,
                              c.Memo,
                              c.IsUsed,
                              NmemberID = s.MemberId,
                              NmemberName = sg.MemberName
                          };

            if (coupons != null)
            {
                foreach (var c in coupons.ToList())
                {
                    CACouponViewModel cvm = new CACouponViewModel();
                    cvm.Fid = c.Fid;
                    cvm.Price = c.Price;
                    cvm.CouponCode = c.CouponCode;
                    cvm.Memo = c.Memo;
                    cvm.Title = c.Title;
                    cvm.IsUsed = c.IsUsed;
                    cvm.NmemberID=c.NmemberID;
                    cvm.NmemberName=c.NmemberName;
                    list.Add(cvm);
                }

            }

            return View(list);
            
        }
        public IActionResult ACouponEdit(string data)
        {
            string result = "0";
            CACouponViewModel cac=JsonConvert.DeserializeObject<CACouponViewModel>(data);
            if (cac != null)
            {
                if (cac.Fid > 0)
                {
                    Coupon coup = _context.Coupons.FirstOrDefault(t => t.Fid == cac.Fid);
                    if (coup != null)
                    {
                        coup.Price = cac.Price;
                        coup.Memo = cac.Memo;
                        coup.Title = cac.Title;
                        coup.IsUsed = cac.IsUsed;
                        
                        Coupon2NormalMember c2n = _context.Coupon2NormalMembers.FirstOrDefault(c => c.CouponId==cac.Fid);
                        if (c2n!=null)
                        {
                            c2n.MemberId = cac.NmemberID;
                        }
                        else
                        {
                            c2n=new Coupon2NormalMember();
                            c2n.MemberId = cac.NmemberID;
                            c2n.CouponId=cac.Fid;
                            _context.Coupon2NormalMembers.Add(c2n);
                                
                        }
                            
                        
                    }
                }else if (cac.Fid==0)
                {
                    Coupon newCoup = new Coupon();                    
                    newCoup.Price = cac.Price;
                    newCoup.Memo = cac.Memo;
                    newCoup.Title = cac.Title;
                    newCoup.IsUsed = cac.IsUsed;
                    newCoup.CouponCode=Guid.NewGuid().ToString().Substring(0,10);
                    _context.Coupons.Add(newCoup);
                    _context.SaveChanges();
                    if (cac.NmemberID!=null)
                    {
                        Coupon2NormalMember c2n = new Coupon2NormalMember();
                                                        
                        c2n.MemberId = cac.NmemberID;

                        int fid = 1;
                        Coupon lastCoup = _context.Coupons.OrderByDescending(c => c.Fid).FirstOrDefault();
                        if (lastCoup != null)
                            fid=lastCoup.Fid;

                        c2n.CouponId=fid;
                        _context.Coupon2NormalMembers.Add(c2n);                            

                    }
                }
                

                _context.SaveChanges();
                result="1";
            }
           
            return Content(result);
            //return NoContent();

        }
        
        public IActionResult ACouponDelete(int id)
        {
            //var coup = await _context.Coupons.FindAsync(id);
            Coupon coup = _context.Coupons.FirstOrDefault(c => c.Fid==id);
            if (coup == null)
            {
                return NotFound();
            }
            Coupon2NormalMember c2n = _context.Coupon2NormalMembers.FirstOrDefault(c => c.CouponId==id);
            if (c2n!=null)
                _context.Coupon2NormalMembers.Remove(c2n);
            _context.Coupons.Remove(coup);
            _context.SaveChanges();

            return RedirectToAction("ACouponList");
        }

        public IActionResult CCouponExchange()
        {
            int memberId = 0;
            List<CACouponViewModel> list=new List<CACouponViewModel>();
            if (HttpContext.Session.Keys.Contains(CDictionary.SK_LOGINED_USER))
            {
                string json = HttpContext.Session.GetString(CDictionary.SK_LOGINED_USER);
                NormalMember user = JsonConvert.DeserializeObject<NormalMember>(json);
                if (user != null)
                {
                    memberId = user.Fid;
                    var coupons = from c2n in _context.Coupon2NormalMembers
                                  join coup in  _context.Coupons on c2n.CouponId equals coup.Fid
                                  into cGroup
                                  from c in cGroup.DefaultIfEmpty()
                                  where c2n.MemberId==memberId && c.IsUsed==1
                                  select new
                                  {
                                      c2n.CouponId,
                                      c.Title,
                                      c.Price,
                                      c.Memo,
                                      c2n.Fid

                                  };
                    foreach(var c in coupons.OrderByDescending(c=>c.Fid))
                    {
                        CACouponViewModel cac = new CACouponViewModel();
                        cac.Fid = (int)c.CouponId;
                        cac.Title = c.Title;
                        cac.Price = c.Price;
                        cac.Memo = c.Memo;
                        cac.NmemberID = memberId;
                        list.Add(cac);
                    }

                }
            }
            return View(list.AsEnumerable());
        }
        
        public IActionResult CSubmitCouponExchange(string data)
        {            
            if (!HttpContext.Session.Keys.Contains(CDictionary.SK_LOGINED_USER))
                return Json("尚未登入會員");

            string json = HttpContext.Session.GetString(CDictionary.SK_LOGINED_USER);
            NormalMember user = JsonConvert.DeserializeObject<NormalMember>(json);
            Coupon coup = _context.Coupons.FirstOrDefault(c => c.CouponCode.Equals(data));
            var coupInfo = from c in _context.Coupons
                          join cn in _context.Coupon2NormalMembers on c.Fid equals cn.CouponId
                          into sGroup
                          from s in sGroup.DefaultIfEmpty()
                          join n in _context.NormalMembers on s.MemberId equals n.Fid
                          into sg2
                          from sg in sg2.DefaultIfEmpty()
                          where c.CouponCode==data
                          select new
                            {
                                c.Fid,
                                c.Price,
                                c.CouponCode,
                                c.Memo,
                                c.Title,
                                c.IsUsed,
                                NmemberID = s.MemberId,
                                NmemberName = sg.MemberName
                            };
            if (user!=null)
            {
                if (coup==null || coup.IsUsed!=1)                
                    return Json("優惠券代碼錯誤");                                
                                    
                if (!string.IsNullOrEmpty(coupInfo.ToList()[0].NmemberName))
                    return Json("優惠券已被兌換過");

                Coupon2NormalMember c2n = new Coupon2NormalMember();
                c2n.MemberId=user.Fid;
                c2n.CouponId=coup.Fid;
                _context.Coupon2NormalMembers.Add(c2n);
                try
                {
                    _context.SaveChanges();
                }
                catch (Exception err)
                {
                    return Json($"error:{err.Message}");
                }

                return Json(coup);
                                    
                    
            }

            return NoContent();
                
        }
        public IActionResult CSimpleLogin(CLoginViewModel login)
        {
            string result = "0";

prjMSIT145-Final/Views/Home/CIndex.cshtml
@model List<prjMSIT145Final.Web.ViewModels.VCUtilityViewModel>
@{
    Layout = "_CustomerLayout";
    ViewData["Title"] = "Home Page";
}
@section Styles{
    <link href="~/css/Customer_css/CMainpagestyle.css" rel="stylesheet" />
    <link href="~/css/Customer_css/CShopcardstyle.css" rel="stylesheet" />
    <style>
        .Bone.Boneposition4{
            cursor:pointer;
        }
    </style>
}
<section class="Displayarea">
    <div class="ADblock">
        <img src="~/images/Customer/Mainpage/shibaLogo_row2.png" />
        @*廣告輪播*@
        <div class="wrapper">
            <ul class="slides">
                @*<li><img class="hidden" src="@Url.Content("~/adminImg/adDisplay/001.jpg")" /></li>*@
            </ul>
        </div>
    </div>
    <div class="Bone Boneposition1 CursorPointer">
        <div class="Quickbutton">
            <img src="~/images/Customer/Mainpage/nearby 64x64.png" />
        </div>
        <p>找附近</p>
    </div>
    <div class="Bone Boneposition2 CursorPointer">
        <div class="Quickbutton">
            <img src="~/images/Customer/Mainpage/findarea 64x64.png" />
        </div>
        <p>找區域</p>
    </div>
    <div class="Bone Boneposition3 CursorPointer">
        <div class="Quickbutton">
            <img src="~/images/Customer/Mainpage/shop 64x64.png" />
        </div>
        <p>找品牌</p>
    </div>
    <div class="Bone Boneposition4 CursorPointer">
        <div class="Quickbutton">
            <img src="~/images/Customer/Mainpage/coupon 64x64.png" />
        </div>
        <p>我的券夾</p>
    </div>
</section>
<section class="ImgDisplay">
    @{
        int Count = 0;
        string png = "";
        foreach (var item in Model[0].AdImgList)
        {
            Count++;
            png = @$"{Url.Content("~/adminImg/adDisplay/")}{item.ImgName}";
            if (Count == 1)
            {
                                <div class="LeftAD" style="background-image:url('@png')"></div>
            }
            else if (Count == 2)
            {
                                <div class="MidAD" style="background-image:url('@png');"></div>
            }
            else if (Count == 3)
            {
                                <div class="RightAD" style="background-image:url('@png');"></div>
            }
        }
    }
</section>
<section class="Showshoptilte">
    <p>專屬推薦店家</p>
    <div>
        <h2>查看更多&ensp;</h2>
        <img src="~/images/Customer/Mainpage/circlearrow_right 32x32.png" />
    </div>
</section>
<section class="Showshopdisplay">
    @{
        foreach (var item in Model[0].BusinessMemberList)
        {
            if (item.IsSuspensed == 0)
            {
                if (item.IsOpened > 0)
                {
                                    @if (item.IsOpened == 1)
                    {
                                        <div class="Shopcard CursorPointer" id="Shop @item.Fid">
                                            <img class="Shopcardcover" src="~/images/@item.SighImgFileName" />
                                            <img class="Shopcardloggo" src="~/images/@item.LogoImgFileName" />
                                            <div class="Shopcardbottem">
                                                <h3>&ensp;@item.MemberName</h3>
                                                <ul>
                                                    <li>&ensp;@item.OpenTime&ensp;～&ensp;@item.CloseTime&ensp;</li>
                                                    <li id="Dis  @item.Fid" class="DisText">&ensp;0.3 km&ensp;</li>
                                                </ul>
                                                <h4>&ensp;@item.Address</h4>
                                            </div>
                                        </div>
                    }
                                    @if (item.IsOpened == 2)
                    {
                                        <div class="Shopcard CursorDefault" id="Shop @item.Fid">
                                            <img class="Shopcardcover" src="~/images/@item.SighImgFileName" />
                                            <img class="Shopcardloggo" src="~/images/@item.LogoImgFileName" />
                                            <div class="ShopisClose">暫停接單</div>
                                            <div class="Shopcardbottem">
                                                <h3>&ensp;@item.MemberName</h3>
                                                <ul>
                                                    <li>&ensp;@item.OpenTime&ensp;～&ensp;@item.CloseTime&ensp;</li>
                                                    <li id="Dis  @item.Fid" class="DisText">&ensp;0.3 km&ensp;</li>
                                                </ul>
                                                <h4>&ensp;@item.Address</h4>
                                            </div>
                                        </div>
                    }
                }
            }
        }
    }
</section>
@section Scripts{
    <script>
        @*let lat = '';
        let long = '';
        let DisDiv = document.getElementsByClassName("DisText");
        navigator.geolocation.getCurrentPosition(successCallback);
        function successCallback(position) {
            lat = position.coords.latitude;
            long = position.coords.longitude;
            SendCurrentLocation(lat, long);
        }
        async function SendCurrentLocation(latitude, longitude) {
            const response = await fetch(`@Url.Content("~/Home/CDistanceCount")?latitude=${latitude}&longitude=${longitude}`);
            const datas = await response.json();
            console.log(datas);
            let index=0;
            for (let i = 0, maxBML = datas[0].businessMemberList.length; i < maxBML; i++) {
                if (datas[0].businessMemberList[i].isSuspensed == 0) {
                    DisDiv[index].innerHTML = `&ensp;${datas[0].businessMemberList[i].distance} km&ensp;`;
                    index++;
                }
            }
        }*@


        @foreach (var item in Model[0].BusinessMemberList)
        {
            if (item.IsSuspensed == 0)
            {
                @if (item.IsOpened == 1)
                {
                    @:document.getElementById("Shop @(item.Fid)").addEventListener("click", function () {
                    @:location.href="/Home/CShowProduct?BFid=@(item.Fid)";
                    @:});
                }
            }
        }

        $(function () {
                let slideNum = 0;
                let slideCount = $(".slides li").length;
                let lastIndex = slideCount - 1;

                let adArr = new Array();
                adArr.push('001.jpg');                
                $.ajax({
                    url: `@Url.Content("~/home/CgetAdImgList")`,
                    type: 'post',
                    data: {},
                    dataType: 'json',
                    success: function (data) {
                        let docFrag = document.createDocumentFragment();
                        $(data).each(function (i, value) {                            
                            $(docFrag).append(`<li><img src='@Url.Content("~/adminImg/adDisplay/")${value.imgName}' /></li>`);
                        });
                        $('ul.slides').append(docFrag);
                        //console.log(adArr);
                    }
                });

                slideNum = 0;
                let si = setInterval(() => {
                    let i = $('ul.slides>li').length + 1;
                    //console.log(i);
                    
                    if (i > 0) {
                        i = i - 1;                       
                        if (slideNum > i) 
                            slideNum = 0;
                                                
                        let slidemove = -540 * slideNum;
                        if (slideNum == 0) 
                            $('ul.slides').addClass('hidden');                        
                        else 
                            $('ul.slides').removeClass('hidden');
                        
                        $('ul.slides').css('left', slidemove);
                        slideNum++;
                    }
                }, 1000);

                $('.Bone.Boneposition4').click(function(){
                    location.assign('@Url.Action("CCoupons2Member","Coupon")');
                });
        });
    </script>
}